
/* =========================================
   *OCN: JavaScript codes generated by ChatGPT(OpenAI, 2025) with custom prompt/edits.
   Code syntax correct by Copilot(GitHub, 2025)
   ========================================= */


// ENTER THE UNIVERSE BUTTON
// =============================   

document.addEventListener("DOMContentLoaded", () => {
  const enterButton = document.getElementById("enterButton");
  if (!enterButton) return;

  enterButton.addEventListener("click", () => {
    document.body.classList.add("entered-universe");
  });
});

// NAVBAR TOGGLE MENU
// =============================

document.addEventListener("DOMContentLoaded", () => {
  const menuToggle = document.querySelector('.menu-toggle');
  const navMenu = document.querySelector('.nav-menu');

  if (menuToggle && navMenu) {
    menuToggle.addEventListener('click', () => {
      menuToggle.classList.toggle('active');
      navMenu.classList.toggle('active');
    });

    navMenu.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        menuToggle.classList.remove('active');
        navMenu.classList.remove('active');
      });
    });
  }
});

// SMOOTH SCROLLING
// =============================

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth' });
      }
    });
  });
});

// INFINITE CAROUSEL DUPLICATION
// =============================

document.addEventListener("DOMContentLoaded", () => {
  const track = document.querySelector('.carousel-track');
  if (track) {
    const items = Array.from(track.children);
    const trackWidth = track.scrollWidth;
    const viewportWidth = track.parentElement.offsetWidth;

    // Clone for smooth looping (at least 2 times the viewport width)
    let totalWidth = trackWidth;
    while (totalWidth < viewportWidth * 2.5) {
      items.forEach(item => {
        const clone = item.cloneNode(true);
        track.appendChild(clone);
      });
      totalWidth = track.scrollWidth;
    }
  }
});

// Pause animation when hovering any toy card
const carousel = document.querySelector('.toy-carousel');
const track = document.querySelector('.carousel-track');

if (carousel && track) {
  carousel.addEventListener('mouseenter', () => {
    track.style.animationPlayState = 'paused';
  });
  carousel.addEventListener('mouseleave', () => {
    track.style.animationPlayState = 'running';
  });
}

// IMPACT STATS COUNT-UP ON SCROLL
// =============================

document.addEventListener("DOMContentLoaded", () => {
  const counters = document.querySelectorAll(".count");
  const options = { threshold: 0.6 };

  const startCount = (entry) => {
    if (!entry.isIntersecting) return;
    const el = entry.target;
    const target = +el.dataset.target;
    let count = 0;
    const increment = target / 60; // adjust speed

    const updateCount = () => {
      count += increment;
      if (count < target) {
        el.textContent = Math.floor(count);
        requestAnimationFrame(updateCount);
      } else {
        el.textContent = target + (el.dataset.target.includes('%') ? '%' : '+');
      }
    };
    updateCount();
    observer.unobserve(el);
  };

  const observer = new IntersectionObserver((entries) => {
    entries.forEach(startCount);
  }, options);

  counters.forEach((el) => observer.observe(el));
});

// FAQ Accordion
// =============================

document.addEventListener("DOMContentLoaded", () => {
  const faqItems = document.querySelectorAll(".faq-item");

  faqItems.forEach(item => {
    const question = item.querySelector(".faq-question");
    question.addEventListener("click", () => {
      item.classList.toggle("active");
      faqItems.forEach(other => {
        if (other !== item) other.classList.remove("active");
      });
    });
  });
});

// FLOATING PLANETS VISIBILITY ON SCROLL
// ===============================================

document.addEventListener("DOMContentLoaded", function () {
  const planets = document.querySelector(".floating-planets");
  const brandStory = document.querySelector(".brand-story");
  const featured = document.querySelector("#ftr-collection");
  const nextSection = document.querySelector(".impact-stats") || document.querySelector("footer");

  // Gộp vùng hiển thị bằng cách lắng nghe Brand Story đến gần section sau
  const observer = new IntersectionObserver(
    (entries) => {
      let visible = false;
      entries.forEach(entry => {
        if (entry.isIntersecting) visible = true;
      });
      planets.classList.toggle("visible", visible);
    },
    {
      root: null,
      threshold: 0.05, // starts slightly earlier and ends slightly later
      rootMargin: "0px 0px -70% 0px" // visible longer before fading out
    }
  );

  observer.observe(brandStory);
  observer.observe(featured);
  if (nextSection) observer.observe(nextSection);
});
